name: GH Actions Testing

on:
  push:
    branches:
      - "main"
  pull_request:
    types:
      - "opened"
      - "reopened"
      - "synchronize"
    branches:
      - "main"

jobs:
  timeout-test:
    runs-on: ubuntu-latest
    steps:
      - name: test timeout
        run: |
          echo "Starting sleep"
          sleep 1500
          echo "Completed sleep"
